---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "..fullname" . }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "..fullname" . }}
rules:
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, watch]
  - apiGroups: [""]
    resources: [namespaces]
    verbs: [list, watch]
  - apiGroups: [admissionregistration.k8s.io/v1, admissionregistration.k8s.io/v1beta1]
    resources: [validatingwebhookconfigurations, mutatingwebhookconfigurations]
    verbs: [create, patch]
  # Extra for multi-namespace
  - apiGroups: [""]
    resources: [events]
    verbs: [create]
  - apiGroups: [ traefik.containo.us ]
    resources: [ middlewares ]
    verbs: [ get, list, watch, create, patch, delete ]
  - apiGroups: [ kodify.io ]
    resources: [ middleglues ]
    verbs: [ get, list, watch, patch ]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "..fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "..fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "..fullname" . }}
    namespace: {{ .Release.Namespace }}

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: Role
# metadata:
#   name: {{ template "..fullname" . }}
#   namespace: {{ .Release.Namespace }}
# rules:
#   - apiGroups: [""]
#     resources: [events]
#     verbs: [create]
#   - apiGroups: [ traefik.containo.us ]
#     resources: [ middlewares ]
#     verbs: [ get, list, watch, create, patch, delete ]
#   - apiGroups: [ kodify.io ]
#     resources: [ middleglues ]
#     verbs: [ get, list, watch, patch ]

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: RoleBinding
# metadata:
#   name: {{ template "..fullname" . }}
#   namespace: {{ .Release.Namespace }}
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: Role
#   name: {{ template "..fullname" . }}
# subjects:
#   - kind: ServiceAccount
#     name: {{ template "..fullname" . }}
