apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: middleglues.drslump.org
spec:
  scope: Namespaced
  group: drslump.org
  names:
    kind: MiddleGlue
    plural: middleglues
    singular: middleglue
    shortNames:
      - mg
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              x-kubernetes-preserve-unknown-fields: true
              properties:
                managedMiddleware:
                  description: traefik middleware to write and update
                  type: string
                sourceMiddlewares:
                  type: array
                  description: traefik middlewares to use as IP sources
                  items:
                    type: string
                ips:
                  type: array
                  description: extra IP addresses to be added to our managed middleware
                  items:
                    type: string
                depth:
                  description: depth parameter of the created middleware
                  type: integer
